### ISSUE TITLE
get method not working v1.9.43

### ISSUE THREAD

**Issue by fernandoval** [BobKnothe/autoNumeric#188]
The method 'get' is throwing error in version 1.9.43

$(selector).autoNumeric('get');

Abort with error **false.test is not a function**

```
Uncaught TypeError: false.test is not a function
  k.get @ autoNumeric-min.js?v=1452213209:35
  e.fn.autoNumeric @ autoNumeric-min.js?v=1452213209:35
  (anonymous function) @ my-products.view.js?v=1452213196:488
  jQuery.event.dispatch @ jquery.js?v=1445956694:4430
  elemData.handle @ jquery.js?v=1445956694:4116
```

Method working perfectly in version 1.9.42

**Comment by BobKnothe** [comment]
Can you post a fiddle?

**Comment by BobKnothe** [comment]
Please post a fiddle
--------- Original Message --------- Subject: [autoNumeric] get method not working v1.9.43 (#188)

**Comment by Steve-Evangelista** [comment]
I encounter the same error when upgrading an existing solution from 1.9.26 - however, I only get the error when using the "-min" version. The unminified version of the library works seamlessly.

**Comment by JimmyThommen** [comment]
Same as Steve-Evangelista. I downloaded the .zip from github yesterday and took the broken -min version and the working unminified version from it.

**Comment by BobKnothe** [comment]
I will re-minimize and post shortly.

I you could test after it would be appreciated

**Comment by fernandoval** [comment]
Solved

**Comment by Steve-Evangelista** [comment]
Same - thanks for the fast turnaround @BobKnothe

**Comment by BobKnothe** [comment]
only if all my issues were this easy to solve - thanks for catching.

**Comment by rstarkov** [comment]
Looks like the latest release on the github Releases page still has this problem.

**Comment by BobKnothe** [comment]
I just tested and do not see the issue.

**Comment by diguin** [comment]
Same problem here. When you download from bower (as I did) the version that you download is the 1.9.43 and this problem is present. 

I tried this code:

` var val= $('#price').autoNumeric('get');
    $('#price').autoNumeric('destroy');
    $('#price').val(val);`

With the minified version it fails, but it works with the unminified version.

**Comment by BobKnothe** [comment]
1.9.45 is the latest 

Will check and see why bower is not updated

 
Robert (Bob) Knothe
